spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_center?useSSL=false
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
